platform: support to elixir different versions

diff --git a/elixir/deploy b/elixir/deploy
--- a/elixir/deploy
+++ b/elixir/deploy
@@ -4,6 +4,25 @@
 # Use of this source code is governed by a BSD-style
 # license that can be found in the LICENSE file.
 
+if [[ $ELIXIR_VERSION ]] ; then
+	echo "-- Using elixir version: $ELIXIR_VERSION --"
+	ELIXIR_REPO=${ELIXIR_REPO:-https://packages.erlang-solutions.com}
+	ELIXIR_TARGET="$ELIXIR_REPO/erlang/elixir/FLAVOUR_2_download/elixir_${ELIXIR_VERSION}~ubuntu~trusty_amd64.deb"
+
+	if ! (curl -s --retry 3 -L $ELIXIR_TARGET -o /tmp/elixir.deb); then
+		echo "ERROR: ruby version $ELIXIR_VERSION is not supported."
+		echo "You will find supported versions here: https://www.erlang-solutions.com/resources/download.html"
+		exit 1
+	fi
+
+	echo "-- Installing elixir version: $ELIXIR_VERSION --"
+	if ! (sudo dpkg -i /tmp/elixir.deb); then
+		echo "ERROR: There was a problem installing the elixir version"
+		exit 1
+	fi
+	rm /tmp/elixir.deb
+fi
+
 SOURCE_DIR=/var/lib/tsuru
 source ${SOURCE_DIR}/base/deploy
 source ${SOURCE_DIR}/base/rc/config
