static: allow usage of other nginx packages
This allow the app to use an customized package, like the nginx-extras.
Also, adds tests for the static platform, related to #19.

diff --git a/static/deploy b/static/deploy
--- a/static/deploy
+++ b/static/deploy
@@ -13,4 +13,17 @@ set +e
 test -e ${CURRENT_DIR}/nginx.conf && sudo mv ${CURRENT_DIR}/nginx.conf /etc/nginx/nginx.conf
 set -e
 
+NGINX_PKG=${NGINX_PKG:-nginx}
+
+case "$NGINX_PKG" in
+    "nginx-core"|"nginx"|"nginx-full"|"nginx-light"|"nginx-extras")
+        dpkg -s $NGINX_PKG &> /dev/null || (sudo apt-get update && sudo apt-get install -qy $NGINX_PKG)
+        ;;
+    *)
+        echo "ERROR: Invalid nginx package $NGINX_PKG."
+        echo "Supported values are: nginx, nginx-core, nginx-full, nginx-light, nginx-extras."
+        exit 1
+        ;;
+esac
+
 ${SOURCE_DIR}/static/validate-nginx-conf /etc/nginx/nginx.conf
